### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by dylanmcreynolds** [SciCatProject/zip-service#97]
I'm trying to get a zip-service instance running locally. 

From the README, I copy the local.config.json into /src, and run:

 `npm install && npm start`

I get the error below. Am I missing a configuration step?

Thanks!

```

> zip-service@0.0.0 prebuild
> tslint -c tslint.json -p tsconfig.json --fix


> zip-service@0.0.0 build
> rm -rf ./dist/ && tsc  && cp -r ./src/views ./dist/

src/routes/upload.ts:65:23 - error TS2339: Property 'tempFilePath' does not exist on type 'UploadedFile | UploadedFile[]'.
  Property 'tempFilePath' does not exist on type 'UploadedFile[]'.

65     req.files.zipfile.tempFilePath
                         ~~~~~~~~~~~~

src/routes/upload.ts:106:59 - error TS2339: Property 'name' does not exist on type 'UploadedFile | UploadedFile[]'.
  Property 'name' does not exist on type 'UploadedFile[]'.

106           `Extracted the file(s) from ${req.files.zipfile.name} to ${savePath}`
```

**Comment by dylanmcreynolds** [comment]
I think this has to do with a compatibility issue with express-upload. 

If I change the dependency in zip-service/package.json from: 
` "@types/express-fileupload": "^1.1.6"`
to
` "@types/express-fileupload": "1.1.5"`

I can build and run. It looks like the type definition for express-upload was changed three months ago, and now clients need to expect either an UploadedFile or UploadedFile[]:

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/20884c1eb823629b6a28f8df90306f215815ab85

It seems to me that my pin of the version is a short term fix, but upload.ts should be enhanced to deal with the possible array.

**Comment by henrikjohansson712** [comment]
Thanks for pointing this out! I will push a fix for this.
